<Project>
  <PropertyGroup>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2027.0.2-preview</MetalamaVersion>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2027.0.2-preview</MetalamaCompilerVersion>
    <MetalamaTestsNopCommerceReleaseVersion>4.5.60</MetalamaTestsNopCommerceReleaseVersion>
    <MetalamaTestsNopCommerceReleaseMainVersion>4.5.60</MetalamaTestsNopCommerceReleaseMainVersion>
  </PropertyGroup>
</Project>