<Project>
  <PropertyGroup>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.27</MetalamaVersion>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.18</MetalamaCompilerVersion>
    <MetalamaTestsNopCommerceReleaseVersion>4.5.59</MetalamaTestsNopCommerceReleaseVersion>
    <MetalamaTestsNopCommerceReleaseMainVersion>4.5.59</MetalamaTestsNopCommerceReleaseMainVersion>
  </PropertyGroup>
</Project>